# Types Module generated by GraphQL-Ruby
module Types
  # The ImageType is the GraphQL type for the Image model
  class ImageType < Types::BaseObject
    description "A type that represents a single Image entity."
    field :id, ID, null: false
    field :title, String, null: false
    field :description, String, null: false
    field :price, Float, null: false
    field :attached_image_url, String, null: false
    field :tags, [Types::TagType], null: false
    field :creator, Types::UserType, null: false
    field :owner, Types::UserType, null: false

    def attached_image_url
      Loaders::ActiveStorageLoader.for(:Image, :attached_image).load(object.id).then do |image|
        Rails.application.routes.url_helpers
          .rails_blob_url(image, only_path: true)
      end
    end

    def tags
      Loaders::AssociationLoader.for(Image, :tags).load(object)
    end

    def creator
      Loaders::AssociationLoader.for(Image, :creator).load(object)
    end

    def owner
      Loaders::AssociationLoader.for(Image, :owner).load(object)
    end
  end
end
