# Types Module generated by GraphQL-Ruby
module Types
  # The PurchaseType is the GraphQL type for the Purchase model
  class PurchaseType < Types::BaseObject
    description "A type that represents a single Purchase entity."
    field :id, ID, null: false
    field :cost, Integer, null: false
    field :image, Types::ImageType, null: false
    field :merchant, Types::UserType, null: false
    field :customer, Types::UserType, null: false

    def image
      Loaders::AssociationLoader.for(Purchase, :image).load(object)
    end

    def merchant
      Loaders::AssociationLoader.for(Purchase, :merchant).load(object)
    end

    def customer
      Loaders::AssociationLoader.for(Purchase, :customer).load(object)
    end
  end
end
