
module Types
  # QueryType is generated by GraphQL-Ruby
  class QueryType < Types::BaseObject
    field :profile, resolver: Queries::Profile
    field :user, resolver: Queries::User
    field :users, resolver: Queries::Users
    field :tags, resolver: Queries::Tags
    field :image, resolver: Queries::Image
    field :image_listed, resolver: Queries::ImagesListed
    field :image_search, resolver: Queries::ImageSearch
    field :purchase, resolver: Queries::Purchase
  end
end
