# Types Module generated by GraphQL-Ruby
module Types
  # The UserType is the GraphQL type for the User model
  class UserType < Types::BaseObject
    description "A user represents someone that may interact with this API."
    field :id, ID, null: false
    field :balance, Integer, null: false
    field :email, String, null: false
    field :role, String, null: false
    field :username, String, null: false
    field :created_images, [Types::ImageType], null: false
    field :owned_images, [Types::ImageType], null: false
    field :purchases, [Types::PurchaseType], null: false
    field :sales, [Types::PurchaseType], null: false

    def created_images
      Loaders::AssociationLoader.for(User, :created_images).load(object)
    end

    def owned_images
      Loaders::AssociationLoader.for(User, :owned_images).load(object)
    end

    def purchases
      Loaders::AssociationLoader.for(User, :purchases).load(object)
    end

    def sales
      Loaders::AssociationLoader.for(User, :sales).load(object)
    end
  end
end
