inherit_from: .rubocop_todo.yml
require:
    - rubocop-rails
    - rubocop-faker
    - rubocop-rspec
inherit_gem:
    rubocop-shopify: rubocop.yml
AllCops:
    NewCops: enable
    Exclude:
        - 'config/environments/development.rb'
        - 'db/migrate/20210507031246_create_image_tags.rb'
