name: Client
'on':
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run Prettier
      run: yarn run format
    - name: Run Jest
      run: yarn run test
